{"_id":"c5c91010-0160-11ed-80b7-e7b2fff5f17b","postId":"2022_03_cancellation-4-polling-2bc2dbc8-929d-3a7d-8b43-4cdda9797b62","postUri":"https://blog.stephencleary.com/2022/03/cancellation-4-polling.html","replyTo":"5718f380-015e-11ed-80b7-e7b2fff5f17b","authorEmailEncrypted":"FhHyt7Rf4eX7ZWLtOunEm8YaQBGdDxcfuZe1FJSxq2FZuXxK2BDNuh5qrMJzZ642LTNCSYfqRDpq75PBlIdwryWJmw+w2IJqjofS7SX0VxtrQ463By5n3lMSSUnuZo8bQJ6v+XjtbRocDQrabjG2myVN+HjLqNtXTyZluxAYhv+DULs3Z7PDQ3Ng/RrmShTH9AKXpisKUepx9+FEc9pwPFjz8KFz94WfVi02B8mNSdyHn1oXKyeFYLAl4nhNvS6grVCEnpY3ZEYk/sL1q7c13s1AAjlmcsAY2h/PKfpN77/7xQ7JqERoEs1Y1DdgXQkV4qKzOfWYdakWYT5ItWkjNo0PaK9u73nG4rJsf3ub8fK/fSqESPjRvDYnc/m9RR7RQ5B5iAScPJB8xgXN+JWrDSunyilyA5FUCXR5aPFNhfVMgcybW/8ky1bbZjW1k2rHMSnj3+X3Ua/wMcwuN4j4Et1tHGUF1utkBbfuA87RbkQ9b62JfC3+4Wbr6Mo6A34i3pxPRD44Rc1Sy4tISmK9SBlBckIscUvnUy4NYWL1Svu/GZ5a5xVRHTrb53rOOlpdNb/y2ZQlp4WbvOGkfG/9YlNvOoPi+AFcUkkFdi3E/0xWTYY8xluvk7MBm2y4SvC7Ze2pQqeA0qTPxdPtKXQmMy5EWOCgaMJTayKQCI24JZ0=","authorEmailMD5":"23448e78d187fba56d8bc263081ac5d8","authorName":"Stephen Cleary","authorUri":"https://stephencleary.com","message":"Yes. It's a bad practice to throw *any* exception from a `Task`-returning non-`async` method. You could argue that [boneheaded exceptions](https://ericlippert.com/2008/09/10/vexing-exceptions/) are an exception to this rule, but exogenous/vexing exceptions such as `OperationCanceledException` should never be thrown directly. They should always be placed on the returned `Task`. Note that the `async` keyword will do this for you.","date":"2022-07-11T21:31:06.693Z"}