{"_id":"a2163967-451e-3cd0-8b54-4aed0002eb2d","authorName":"Anthony","authorEmailEncrypted":"FPyhTMnp3LuCqWWBycT0mbgGTV0MiFikdk1lrCYZQLyx7VTT+kmOV9DzB+dbD53HUr9olyJa7+SaVtPkEiEFiOmHINPgSjX4pZY29dyopKlIUijJ7yqq+acb3PVz3TQr3gj8DwDUf+v+hV+Io1oSSfX6/NPhB+LXPPQasz0gi4bdBz3T/J1tbrwuIbSTeP/jDt34cksWrU5f6xi1m82RQT/8oyp3vnSi3kJh0tfmJd5sQofJupHOXCM67B5F2nB03HkjR7/S0Q50UgMwoTsbBQ718dguJEilpNCCcwUyToR7YxbyGNznfSIzOnQXZrQ16KVnvXc4U3WpyGu85tkyUz0ifgzMevudXvslPBsHgmB6xAbylQvRFXYiVY/h7TugpxTqVOsRf9uTlI/Prp6ZHB8p05IRXZEmlhajIIucqPEPRVDlX/xXKZN7CHqeD4WhH0MQlzcXR7Fh39w+Xc87KZIE7ntf08tGkOCVKZYgC3+RleVavIfKRLwbWgyC/qtU7yAzTLSXPKLToZnVmCWztk6yjuPzOYWzYnKMsE6aDk6XlyRQ5IQFQF/iXK5NA7dr9do5J4K2++YZpbqZ1mK1NYyvbE8a9Kk8Ay2vIjEJipBsAackh0C77dy3+US0h/2E2ErHf1DLRtPmtKulgKDwmQMI+iiFku6E2bYuREw+lkA=","authorEmailMD5":"46a5e710fa0a76871082bc7ed7b61c5f","message":"if i try catch inside of a task, then i have to use the dispatcher to display error dialog on ui thread","postId":"2014_04_announcement-msdn-async-mvvm-articles-b2165e1d-7e99-386d-b481-ed64583f3ab7","replyTo":"219201c9-57b9-3091-a4cf-af4aabfe7867","date":"2017-03-07T01:27:24Z","timestamp":1488850044,"authorUserId":"disqus:crosscourtac"}